#!/bin/bash

ALPINE_VERSION=3.11
POSTFIX_VERSION=3.4.9-r0
[ -n "$1" ] && ALPINE_VERSION="$1"
[ -n "$2" ] && POSTFIX_VERSION="$2"

ARCH=$(arch)
[ "$ARCH" = "x86_64" ] && ARCH=amd64

docker build --rm \
    --build-arg ALPINE_VERSION=$ALPINE_VERSION \
    --build-arg POSTFIX_VERSION=$POSTFIX_VERSION \
    -t docker.io/nimbix/postfix:${ALPINE_VERSION}_${POSTFIX_VERSION}-$ARCH .

docker push docker.io/nimbix/postfix:${ALPINE_VERSION}_${POSTFIX_VERSION-$ARCH}

