#!/bin/bash

ALPINE_VERSION=3.11
POSTFIX_VERSION=3.4.12-r0
[ -n "$1" ] && ALPINE_VERSION="$1"
[ -n "$2" ] && POSTFIX_VERSION="$2"

REGISTRY=gcr.io
REPOSITORY=jarvice
PLATFORMS="linux/amd64,linux/ppc64le,linux/arm64"

BUILDER=multiarch

docker buildx build --rm \
    --builder $BUILDER \
    --platform $PLATFORMS --push \
    --build-arg ALPINE_VERSION=$ALPINE_VERSION \
    --build-arg POSTFIX_VERSION=$POSTFIX_VERSION \
    -t $REGISTRY/$REPOSITORY/postfix:${ALPINE_VERSION}_${POSTFIX_VERSION-$ARCH} \
    -f Dockerfile .

